language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip3 install pycryptodome
  - pip3 install coverage coveralls
  - pip3 install -e .
# command to run tests
script:
  - python3 tests/pyfpe_ff3_test.py
  - coverage run --source pyfpe_ff3 -m unittest tests/pyfpe_ff3_test.py
after_success:
  - coveralls